### ISSUE TITLE
Refactoring needed

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/bash-prompt#11]
The script is growing and currently it seems a bit cluttered.
Putting in functions and have it in a more structured way, would be nice.

ideas welcome ;)

**Comment by dschier-wtd** [comment]
This request should be pending until the new bash-preexec/bash-precmd repo is done.
I assume ~3 weeks of work for this.

**Comment by dschier-wtd** [comment]
Soooo, after some thinking what/how we can have this thing here done right. The basic idea would be:

- all different functions (like error handling, usercount, dsiplaying more information) should be done in dedicated functions
- the complete script should extend the existing PROMPT_COMMAND
- PROMPT_COMMAND can have a lot of weird stuff in it

```
PROMPT_COMMAND="foo"
PROMPT_COMMAND="foo;"
PROMPT_COMMAND=""
```
this is a problem, because we have to work around this during extending the PROMPT_COMMAND. A function should parse the content and determine, if something is in the PROMPT_COMMAND, if it ends with a semicolon and extend the PROMPT_COMMAND properly (including a trailing semicolon)

**Comment by Cinux90** [comment]
In case of re-factoring or something like that. An non-executable install.sh script within the released .zip whould be awesome. :)

In the bash-behaviour the install.sh script is non-executable :)
